variables:
  SampleName: SPDSample
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - deploy

build_dx12:
  tags:
  - windows
  - amd64
  stage: build
  artifacts:
    untracked: true
  script:
  - 'cmake -S sample -B sample/build/DX12 -G "Visual Studio 15 2017" -A x64 -DGFX_API=DX12'
  - 'cmake --build sample/build/DX12'

build_vk:
  tags:
  - windows
  - amd64
  stage: build
  artifacts:
    untracked: true
  script:
  - 'cmake -S sample -B sample/build/Vk -G "Visual Studio 15 2017" -A x64 -DGFX_API=VK'
  - 'cmake --build sample/build/Vk'

package_sample:
  tags:
  - windows
  - amd64
  stage: deploy
  dependencies:
    - build_dx12
    - build_vk
  script:
  - echo "Packaging build"
  artifacts:
      name: "%SampleName%-%CI_COMMIT_TAG%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHORT_SHA%"
      paths:
      - LICENSE.txt
      - sample/bin/dxcompiler.dll
      - sample/bin/dxil.dll
      - sample/bin/amd_ags_x64.dll
      - sample/bin/brdfLut.dds
      - sample/bin/%SampleName%_VK.exe
      - sample/bin/%SampleName%_DX12.exe
      - sample/bin/ShaderLibDX
      - sample/bin/ShaderLibVK
      - sample/media/